Feature/problems cards
gencat/decidim-challenges pull request #10
Opened 2020-11-20 07:54 UTC by spuigmitjadxc

2020-11-29 17:38 UTC, tramuntanal reviewed
Good @spuigmitjadxc !
Just some details to review

2020-11-29 17:38 UTC, tramuntanal commented on app/cells/decidim/problems/problem_m/show.erb
> +        <%#= cell("decidim/coauthorships", problem, has_actions: false, context: { current_user: current_user }) %>
remove

2020-11-29 17:38 UTC, tramuntanal commented on app/cells/decidim/problems/problem_m/show.erb
> +                <span class="card__text--paragraph--estat"><%= t(resource_state, scope: 'decidim.problems.states') %></span>
This should be rendered with all letters upcase, in challenges I got it rendered as normal text, but should be as follows in both challenges and problems:
![imatge](https://user-images.githubusercontent.com/199462/100548873-b4bd5e00-326f-11eb-97db-012fea1f03b3.png)

2020-11-29 17:38 UTC, tramuntanal commented on app/cells/decidim/problems/problem_m/show.erb
> +                <span class="card__text--paragraph--estat"><%= t(resource_state, scope: 'decidim.problems.states') %></span>
Also use always English in the code. Rename `card__text--paragraph--estat` please

2020-11-29 17:38 UTC, tramuntanal commented on app/views/decidim/problems/problems/show.html.erb
> +      <!-- embed_modal_for participatory_process_participatory_process_widget_url(current_participatory_space, format: :js)  -->
remove

2020-11-29 17:38 UTC, tramuntanal commented on config/locales/ca.yml
> +        return_to_list: Tornar al llistat
```suggestion
        return_to_list: Torna al llistat
```

2020-11-29 17:38 UTC, tramuntanal commented on spec/cells/decidim/problems/problem_cell_spec.rb
> +        expect(html).to have_css(".card--problem")
Can we also check the contents of the problem are rendered?

2020-11-29 17:38 UTC, tramuntanal commented on spec/cells/decidim/problems/problem_m_cell_spec.rb
> +        expect(cell_html).to have_css(".card--problem")
Can we also check the contents of the problem are rendered?

2020-12-02 14:36 UTC, Leusev requested changes
Looks good for me @spuigmitjadxc 
Only a couple of things:
1. Could you check with rubocop lint test please?
![image](https://user-images.githubusercontent.com/9702463/100886176-d018ab00-34b3-11eb-8634-bc40f0f4d62d.png)

2. When PR #7 is reviewed/merged with master, then you'll could merge this PR from master in order to automatically fix most PR errors

2020-12-02 17:23 UTC, tramuntanal commented
PR #7 has been merged

2020-12-04 12:51 UTC, Leusev requested changes
We already have merged PRs #11  #13 and  #15, do master merge please :smile:

2020-12-09 14:23 UTC, Leusev commented
Hi @spuigmitjadxc 
Could you check Lint tests please?
Thanks!

2020-12-10 10:45 UTC, tramuntanal commented
Hi @spuigmitjadxc I've executed the tests locally and 9 out of 26 are failing:
![imatge](https://user-images.githubusercontent.com/199462/101761935-0e7a1f80-3add-11eb-9eb6-e1d1fc655ecc.png)

Please make sure all tests succeed

2020-12-14 11:34 UTC, spuigmitjadxc commented
PR migred to #17 cause 14 commits aren't from this branch

2020-12-14 11:34 UTC, closed without merging