Add solutions cards
gencat/decidim-challenges pull request #14
Opened 2020-12-02 09:30 UTC by spuigmitjadxc

2020-12-02 14:45 UTC, Leusev requested changes
Looks pretty good, just a couple of little things commented on :wink: 

1. Check rubocop lints please
![image](https://user-images.githubusercontent.com/9702463/100887467-4cf85480-34b5-11eb-9915-c95fad7cb91f.png)

2. Same here, when PR #7 is reviewed/merged with master, you'll could do a merge from master here in order to fix failing tests

Thanks!! :smile:

2020-12-02 14:45 UTC, Leusev commented on app/assets/config/decidim_challenges_manifest.js
> +//= link_directory ../stylesheets/decidim/challenges .css
Is this space between `challenges` and `.css` left on purpose?
Same with `solutions` and `.css`

2020-12-02 14:45 UTC, Leusev commented on app/cells/decidim/solutions/solution_m/show.erb
> +                        <img alt="Logo SDG <%= resource_sdg_index%>" src="/assets/decidim/sdgs/ods-<%= resource_sdg_index%>.svg" class="solution--view">
Maybe it would be better using a translation tag than harcoded text here

2020-12-02 17:28 UTC, tramuntanal commented
PR #7 has already been merged @spuigmitjadxc 

Can you also resolve merge conflicts and check that all specs related to solutions cards succeed please?

2020-12-04 12:51 UTC, Leusev requested changes
We already have merged PRs #11  #13 and  #15, do master merge please :smile:

2020-12-09 14:21 UTC, Leusev commented
Hi @spuigmitjadxc 
can you merge master with this PR please? 
Thanks!

2020-12-09 14:22 UTC, Leusev commented
Hi @spuigmitjadxc 
same here, merge with master please. Furthermore could you check Lint tests please?
Thanks!

2020-12-15 15:12 UTC, merged