catch sdg null error on challenge
gencat/decidim-challenges pull request #20
Opened 2020-12-16 14:42 UTC by spuigmitjadxc

2020-12-16 15:38 UTC, Leusev requested changes

2020-12-16 15:38 UTC, Leusev commented on app/views/decidim/challenges/challenges/show.html.erb
> +                <img alt="Logo ODS <%= (1 + Decidim::Sdgs::Sdg.index_from_code(@challenge.sdg_code.to_sym)).to_s.rjust(2, "0") %>"
Try to minimize business logic in the workforce please. 
You can solve this using some conditionals with the params that you may have prepared in the controller

2020-12-16 15:38 UTC, Leusev commented on app/controllers/decidim/challenges/challenges_controller.rb
>          @challenge = Challenge.find(params[:id])
Maybe here, you could initialize this deleted vars with some conditionals.
E.g.:
```
@sdg = @challenge.sdg_code if @challenge.sdg_code.present?
@sdg_index = (1 + Decidim::Sdgs::Sdg.index_from_code(@challenge.sdg_code.to_sym)).to_s.rjust(2, "0") if @sdg
```
or something like that...

2020-12-16 16:34 UTC, spuigmitjadxc commented
@Leusev, all changes done

2020-12-17 07:27 UTC, Leusev approved these changes
Ok, looks good for me @spuigmitjadxc :+1:

2020-12-17 08:16 UTC, merged